### ISSUE TITLE
Plot of data2 with exact same code is a different (and peak detection is worse) than in documentation 

### ISSUE THREAD

**Issue by signekb** [paulvangentcom/heartrate_analysis_python#37]
Hi Paul,

I tried using your documentation (https://buildmedia.readthedocs.org/media/pdf/python-heart-rate-analysis-toolkit/latest/python-heart-rate-analysis-toolkit.pdf) to make the plot using data2 (pp. 11-12). However, when I plot it (using the same exact code as in the documentation), I get the following plot which is clearly different from the one in the documentation: 
<img width="1240" alt="Screenshot 2019-11-07 at 16 59 17" src="https://user-images.githubusercontent.com/40836345/68407702-51ecb680-0184-11ea-97fd-a4dc2b04e8f8.png">

Picture from the documentation:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/40836345/68417704-3048fa80-0197-11ea-9f83-9c1de391693b.png">

In my version, the rolling average is clearly visible (and seems rather high), and, thus, it misses some peaks that your version of the plot includes. 

Could this be due to something in the toolkit? Or maybe I am doing something wrong?

I downloaded and ran it today. 

Thank you in advance! 

Best, 

SigneKB

**Comment by paulvangentcom** [comment]
You're right it's due to the toolkit. HeartPy has undergone a few expansions and improvements. I'll update the image in the documentation to reflect this.

I wouldn't say peak detection is worse, it's become more conservative at sections surrounding noise, as it was found that sometimes noisy parts would contain incorrectly accepted peaks (which are the most detrimental to HRV analysis). Less accepted peaks might actually be a better fit if the HRV metrics better reflect the underlying signal. 
See also our paper here: https://doi.org/10.1016/j.trf.2019.09.015

You can coax a bit more out of the signal by applying a bandpass filter:

```python
import heartpy as hp

data, timer = hp.load_exampledata(1)
fs = hp.get_samplerate_mstimer(timer)

#filter the signal with a bandpass filter
ft = hp.filter_signal(data, cutoff=[0.5, 3.5], sample_rate = fs, filtertype='bandpass')

wd, m = hp.process(hp.scale_data(ft), fs, clean_rr = True)
hp.plotter(wd, m)
```

Which leads to:

![Figure_1](https://user-images.githubusercontent.com/15799488/68455021-9adf5200-01fa-11ea-9972-f9f5075c8b79.jpeg)

However, a note of caution: the filtering pushes the noise in the beginning into expected ranges, by taking out everything below .5Hz and above 3.5Hz, and I'm not convinced the few accepted peaks around sample 3800 are really heart beats... 

Single accepted peaks (meaning surrounded by rejected peaks) don't matter, they are not used in the analysis anyhow.

Cheers
Paul

**Comment by paulvangentcom** [comment]
A second change has been pushed under: dea78271869f5ec26ed31a68dacf44bdb360aa2d

It makes the visualisation of the moving average optional through the argument moving_average=True/False in the hp.plotter() function.

The moving average used to not be visualised. It is not important for the output, it is only used during peak detection.
