### ISSUE TITLE
Threshold algorythm

### ISSUE THREAD

**Issue by yurasmol** [paulvangentcom/heartrate_analysis_python#6]
If the first stage of signal have the distortions, the second (good) stage fully marked as rejected
[bad_samp.pdf](https://github.com/paulvangentcom/heartrate_analysis_python/files/2775790/bad_samp.pdf)
[good_samp.pdf](https://github.com/paulvangentcom/heartrate_analysis_python/files/2775791/good_samp.pdf)

**Comment by paulvangentcom** [comment]
Hi Yurasmol,

Interesting. Can you provide the raw data files for me? I'll have a look.

Cheers,
Paul

**Comment by yurasmol** [comment]
Hi Paul!

This is my RAW signal (sample rate is 100 Hz) and the test module where I four times cut 1/3 starting portion (noisy) of the signal.
I think that your threshold algorythm get information from the start portion of a signal (noisy in my case) and therefore rest of signal marked rejected.

Yuri

  ----- Original Message -----

**Comment by paulvangentcom** [comment]
Can  you send the RAW.txt file to info@paulvangent.com? I cannot open it from here.

Cheers,
Paul

**Comment by paulvangentcom** [comment]
Yes I see what's happening. It tries to minimize certain parameters globally. Usually a process that gives good results by default, except when a large enough portion of the signal is noisy like here. I will flag this since the current method needs to be refined and I need to allot some time for this soon.

For now a solution is to use the built-in peak enhancer `enhance_peaks` and `butter_lowpass_filter` filtering methods:

```python
import heartpy as hp

data = hp.get_data('RAW.txt')
filtered = hp.butter_lowpass_filter(data, 5, 100.0, 3) #third order butterworth with cutoff @ 5Hz
filtered_and_scaled = hp.scale_data(filtered)

wd, measures = hp.process(filtered_and_scaled, 100.0, reject_segmentwise=True, calc_freq=True)

hp.plotter(wd, measures)
```

Yielding:
![yurasmol_filtered](https://user-images.githubusercontent.com/15799488/52279469-ef972900-2959-11e9-8f93-4e0bb11c2d16.png)

As mentioned it is a suboptimal solution that throws away a portion of the signal. I will close this issue and make it a point on the to-do to refine the methods.
